apiVersion: v1
kind: Namespace
metadata:
  name: mialkin
---
apiVersion: v1
kind: Secret
metadata:
  name: dict
  namespace: mialkin
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5naXRsYWIuY29tIjp7InVzZXJuYW1lIjoiZGljdCIsInBhc3N3b3JkIjoiSzRvS2RKZEwtOTZERmdrOXNaaTEiLCJhdXRoIjoiWkdsamREcExORzlMWkVwa1RDMDVOa1JHWjJzNWMxcHBNUT09In19fQ==
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Service
metadata:
  name: dict
  namespace: mialkin
spec:
  selector:
    app: dict
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dict
  namespace: mialkin
  labels:
    app: dict
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dict
  template:
    metadata:
      namespace: mialkin
      labels:
        app: dict
    spec:
      containers:
        - name: dict
          image: registry.gitlab.com/mialkin/dict.mialkin.ru
          ports:
            - containerPort: 80
          env:
          - name: ADMIN_USERNAME
            value: "aleksei"
          - name: ADMIN_PASSWORD
            value: "jPmPmWBClspIUY3f"
      imagePullSecrets:
        - name: dict
