apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dict
  namespace: mialkin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  storageClassName: linode-block-storage-retain
